name: Build and push image and chart
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    name: Check pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - run: make test

  lint:
    name: Checks and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - run: make staticcheck
      - run: make deadcode
      - run: make vulncheck
      - name: Check code format and run code generators
        run: |
          make fmt
          echo "checking for diff after running generators and formatters, if this fails, run 'make fmt'"
          git diff --name-only | xargs -r git diff --exit-code --

  build_push:
    permissions:
      contents: read
      id-token: write
    if: github.triggering_actor != 'dependabot[bot]'
    name: Build and push
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build-push-sign.outputs.version }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - run: go version
      - name: Build
        run: make build
      - name: Build and push image and SBOM to Nais OCI registry
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: dapla-platform
